version: "2"
linters:
  settings:
    staticcheck:
      checks:
        - all
        - '-QF1008' # could remove embedded field "<SomeField>" from selector
        - '-QF1011'
        - '-ST1000' # at least one file in a package should have a package comment (staticcheck)
        - '-ST1003' # should not use underscores in Go names; method EnterFor_next_loop should be EnterForNextLoop (staticcheck)
        - '-ST1023'
