name:  CI Action
on: [push]
jobs:
  CI:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
    runs-on: ${{matrix.os}}
    steps:
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - run: go version
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: latest
      - run: make test
      - run: make compile
      - name: Upload package as artifact
        uses: actions/upload-artifact@v2
        with:
          name: rcalc-${{matrix.os}}
          path: |
            bin/rcalc
